apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-app
  template:
    metadata:
      labels:
        app: front-app
    spec:
      containers:
        - name: python-app
          image: us.gcr.io/amal-348512/demo:v1
          ports:
            - containerPort: 8000     
          envFrom:
            - configMapRef: 
               name: cm
            
            